version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    depends_on:
      - rabbitmq
    command: ["python", "./src/producer.py"]